spring:
  application:
    name: secureBoardKafka

  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/spring_security_study'
    username: 'root'
    password: '53265326'

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: "swkoqfjojkjavjwjawoojpopfpo1@$@%#osffojofjfoj"
  expiration: 3600000 # 1 hour